#!/bin/bash -l
### running on 2 nodes with 20 cores per node = 2*20 = 40 mpi tasks
#SBATCH --job-name=test-1
##SBATCH --output=test-pw.o%j
#SBATCH --partition=work
##SBATCH --partition=devel
#SBATCH --nodes=6
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=20
#SBATCH --time=24:00:00
#SBATCH --export=NONE
##SBATCH --get-user-env
##SBATCH --exclude=m[0108-0109,0147]
##SBATCH -w, --nodelist=m[0101-0104]
echo "Starting: $(date)"
unset SLURM_EXPORT_ENV

module purge
module load intel64/19.1up00

export CPMD="/bin/cpmd.x"

cd $SLURM_SUBMIT_DIR 

export PP_LIBRARY_PATH="/PP/"
export F_UFMTENDIAN=big

input=job.in
cd $SLURM_SUBMIT_DIR

output=OUT

cp ../LATEST .
cp ../RESTART.* .

mpirun   $CPMD ${input} $PP_LIBRARY_PATH >> ${output}  

